In [1]:
import pandas as pd

<h3>Read summarized_trajectories</h3>

In [2]:
summarized_trajectory_df = pd.read_csv('./data/summarized_trajectory.csv')
display(summarized_trajectory_df)

,flight_id,latitude_count,latitude_mean,latitude_std,latitude_min,latitude_25percentile,latitude_median,latitude_75percentile,latitude_max,longitude_count,...,temperature_75percentile,temperature_max,specific_humidity_count,specific_humidity_mean,specific_humidity_std,specific_humidity_min,specific_humidity_25percentile,specific_humidity_median,specific_humidity_75percentile,specific_humidity_max
0,248750643,11897,45.557291,2.243508,41.182526,43.813849,45.851440,47.226687,49.016327,11897,...,219.807752,287.429532,11897,0.000508,0.001359,0.000006,0.000014,0.000020,0.000039,0.007216
1,248750690,12906,51.337336,5.699563,41.182111,46.464821,51.788471,56.509117,59.666189,12906,...,224.325133,281.127092,12906,0.000304,0.000878,0.000005,0.000016,0.000023,0.000030,0.005494
2,248750693,3635,42.164756,0.460882,41.182530,41.861533,42.260447,42.584450,42.696831,3635,...,268.323309,283.739072,3635,0.001482,0.001644,0.000006,0.000339,0.000378,0.002362,0.005527
3,248750694,12413,49.952583,5.000874,41.180603,45.721653,50.156498,54.347855,57.641167,12413,...,218.413790,281.157377,12413,0.000390,0.001066,0.000003,0.000013,0.000020,0.000026,0.005519
4,248750710,7816,43.353786,0.918070,41.179871,42.793210,43.653488,43.882604,44.630264,7816,...,235.266630,287.651388,7816,0.000558,0.001281,0.000006,0.000008,0.000010,0.000192,0.005560
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
534112,258074448,4350,48.622138,1.429781,46.214676,47.201658,48.990051,50.048538,50.166275,4350,...,283.473741,289.544959,4350,0.003312,0.003246,0.000016,0.000168,0.002238,0.006575,0.007986
534113,258074468,4864,51.221165,1.907152,48.045319,49.457360,51.434117,53.038719,53.750198,4864,...,265.578487,288.535544,4864,0.001669,0.002543,0.000010,0.000048,0.000169,0.002414,0.008585
534114,258074471,10994,48.924019,4.449353,41.180466,45.049842,49.094398,52.838858,55.774283,10994,...,223.355169,282.302024,10994,0.000611,0.001518,0.000003,0.000031,0.000042,0.000074,0.006643
534115,258074485,2418,47.003726,0.433726,46.241409,46.580163,47.118530,47.448704,47.462893,2418,...,288.561217,288.884297,2418,0.004061,0.002374,0.000031,0.000985,0.004625,0.006626,0.007395
534116,258074488,4273,48.092001,0.666757,47.401816,47.448509,47.856354,48.879151,49.064438,4273,...,279.127652,288.761667,4273,0.002412,0.002576,0.000019,0.000099,0.000751,0.004469,0.007492

<h3>Add trajectories to challenge set</h3>

In [3]:
challenge_set_df = pd.read_csv('./data/processed_challenge_set.csv')
display(challenge_set_df)

,flight_id,month_day,month,day,actual_offblock_time_hour_minute,actual_offblock_time_hour,actual_offblock_time_minute,adep,country_code_adep,arrival_time_hour_minute,...,arrival_time_minute,ades,country_code_ades,aircraft_type,wtc,airline,flight_duration,taxiout_time,flown_distance,tow
0,248763780,01-01,1,1,13:46,13,46,EGLL,GB,15:04,...,4,EICK,IE,A320,M,a73f82288988b79be490c6322f4c32ed,61,18,321,54748.000000
1,248760618,01-01,1,1,09:55,9,55,LEBL,ES,19:37,...,37,KMIA,US,B772,H,5543e4dc327359ffaf5b9c0e6faaf0e1,570,13,4193,185441.000000
2,248753824,01-01,1,1,09:39,9,39,ESSA,SE,19:08,...,8,KORD,US,A333,H,8be5c854fd664bcb97fb543339f74770,554,15,3770,230396.000000
3,248753852,01-01,1,1,11:04,11,4,LSZH,CH,19:32,...,32,KPHL,US,B788,H,5543e4dc327359ffaf5b9c0e6faaf0e1,497,11,3607,157615.000000
4,248755934,01-01,1,1,12:36,12,36,EIDW,IE,13:44,...,44,EGLL,GB,A21N,M,a73f82288988b79be490c6322f4c32ed,55,14,305,70318.447226
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
369008,258058361,12-31,12,31,09:38,9,38,LFPG,FR,19:03,...,3,KMIA,US,B788,H,5543e4dc327359ffaf5b9c0e6faaf0e1,545,21,4046,163438.000000
369009,258071247,12-31,12,31,09:27,9,27,LTFM,TR,12:29,...,29,EDDB,DE,A21N,M,6351ec1b849adacc0cbb3b1313d8d39b,158,25,946,78707.000000
369010,258059152,12-31,12,31,09:52,9,52,EDDL,DE,11:41,...,41,EIDW,IE,A320,M,a73f82288988b79be490c6322f4c32ed,99,11,522,62942.750000
369011,258072276,12-31,12,31,09:37,9,37,LFPG,FR,11:13,...,13,EIDW,IE,A21N,M,a73f82288988b79be490c6322f4c32ed,84,12,466,72611.161024
369012,258069969,12-31,12,31,09:38,9,38,LEMD,ES,17:26,...,26,KJFK,US,B772,H,5543e4dc327359ffaf5b9c0e6faaf0e1,453,16,3213,195373.000000

In [4]:
merged_challenge_df = pd.merge(challenge_set_df, summarized_trajectory_df, on='flight_id', how='left')
display(merged_challenge_df)

,flight_id,month_day,month,day,actual_offblock_time_hour_minute,actual_offblock_time_hour,actual_offblock_time_minute,adep,country_code_adep,arrival_time_hour_minute,...,temperature_75percentile,temperature_max,specific_humidity_count,specific_humidity_mean,specific_humidity_std,specific_humidity_min,specific_humidity_25percentile,specific_humidity_median,specific_humidity_75percentile,specific_humidity_max
0,248763780,01-01,1,1,13:46,13,46,EGLL,GB,15:04,...,268.945607,288.078244,3614.0,0.001569,0.002304,0.000003,0.000022,0.000114,0.002915,0.008067
1,248760618,01-01,1,1,09:55,9,55,LEBL,ES,19:37,...,221.850708,298.691536,10358.0,0.001025,0.003064,0.000002,0.000028,0.000044,0.000085,0.013049
2,248753824,01-01,1,1,09:39,9,39,ESSA,SE,19:08,...,241.223833,272.897641,12932.0,0.000512,0.000983,0.000003,0.000016,0.000022,0.000190,0.003214
3,248753852,01-01,1,1,11:04,11,4,LSZH,CH,19:32,...,231.613519,286.518770,17534.0,0.000886,0.002158,0.000002,0.000006,0.000018,0.000154,0.008750
4,248755934,01-01,1,1,12:36,12,36,EIDW,IE,13:44,...,275.224544,288.014789,3265.0,0.002256,0.002640,0.000014,0.000029,0.000719,0.004477,0.008008
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
369008,258058361,12-31,12,31,09:38,9,38,LFPG,FR,19:03,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
369009,258071247,12-31,12,31,09:27,9,27,LTFM,TR,12:29,...,221.953594,290.137029,9519.0,0.000698,0.001855,0.000003,0.000024,0.000040,0.000053,0.008280
369010,258059152,12-31,12,31,09:52,9,52,EDDL,DE,11:41,...,248.321020,289.537153,5952.0,0.001027,0.001972,0.000003,0.000020,0.000026,0.000880,0.008802
369011,258072276,12-31,12,31,09:37,9,37,LFPG,FR,11:13,...,258.227824,286.721784,5068.0,0.001184,0.001979,0.000005,0.000022,0.000029,0.001657,0.007904
369012,258069969,12-31,12,31,09:38,9,38,LEMD,ES,17:26,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
merged_challenge_df.to_csv("./data/challenge_set_with_trajectories.csv", index=False)
print(f"./data/challenge_set_with_trajectories.csv is saved!")

./data/challenge_set_with_trajectories.csv is saved!

<h3>Add trajectories to submission set</h3>

In [6]:
submission_set_df = pd.read_csv('./data/processed_submission_set.csv')
display(submission_set_df)

,flight_id,month_day,month,day,actual_offblock_time_hour_minute,actual_offblock_time_hour,actual_offblock_time_minute,adep,country_code_adep,arrival_time_hour_minute,...,arrival_time_minute,ades,country_code_ades,aircraft_type,wtc,airline,flight_duration,taxiout_time,flown_distance,tow
0,248753821,01-01,1,1,09:44,9,44,LTFJ,TR,12:48,...,48,LFLL,FR,B738,M,6351ec1b849adacc0cbb3b1313d8d39b,170,15,1122,NaN
1,248753822,01-01,1,1,09:45,9,45,EBBR,BE,17:49,...,49,KJFK,US,A333,H,bdeeef3a675587d530de70a25d7118d2,470,15,3205,NaN
2,248754498,01-01,1,1,01:52,1,52,KMIA,US,09:55,...,55,EGLL,GB,B77W,H,5543e4dc327359ffaf5b9c0e6faaf0e1,473,10,3965,NaN
3,248757623,01-01,1,1,08:20,8,20,EGCN,GB,11:06,...,6,LEAL,ES,B38M,M,3922524069809ac4326134429751e26f,156,10,986,NaN
4,248763603,01-01,1,1,11:01,11,1,EIDW,IE,13:00,...,0,LFLL,FR,A320,M,a73f82288988b79be490c6322f4c32ed,105,15,686,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
105954,258066302,12-31,12,31,09:36,9,36,LTFJ,TR,13:12,...,12,EKCH,DK,B38M,M,6351ec1b849adacc0cbb3b1313d8d39b,201,15,1199,NaN
105955,258068609,12-31,12,31,09:49,9,49,LOWW,AT,19:38,...,38,KIAD,US,B763,H,5d407cb11cc29578cc3e292e743f5393,575,14,3937,NaN
105956,258068876,12-31,12,31,09:25,9,25,LTFM,TR,12:24,...,24,LSZH,CH,A321,M,6351ec1b849adacc0cbb3b1313d8d39b,154,25,988,NaN
105957,258064675,12-31,12,31,10:04,10,4,EHAM,NL,10:55,...,55,EDDF,DE,A320,M,f502877cab405652cf0dd70c2213e730,42,9,240,NaN
105958,258058370,12-31,12,31,09:40,9,40,UBBB,AZ,12:28,...,28,LTFM,TR,B738,M,6351ec1b849adacc0cbb3b1313d8d39b,158,10,1014,NaN

In [7]:
merged_submission_df = pd.merge(submission_set_df, summarized_trajectory_df, on='flight_id', how='left')
display(merged_submission_df)

,flight_id,month_day,month,day,actual_offblock_time_hour_minute,actual_offblock_time_hour,actual_offblock_time_minute,adep,country_code_adep,arrival_time_hour_minute,...,temperature_75percentile,temperature_max,specific_humidity_count,specific_humidity_mean,specific_humidity_std,specific_humidity_min,specific_humidity_25percentile,specific_humidity_median,specific_humidity_75percentile,specific_humidity_max
0,248753821,01-01,1,1,09:44,9,44,LTFJ,TR,12:48,...,224.281845,288.199209,10271.0,0.000368,0.000948,0.000005,0.000021,0.000028,0.000078,0.005248
1,248753822,01-01,1,1,09:45,9,45,EBBR,BE,17:49,...,223.176139,286.131558,15629.0,0.000811,0.001957,0.000003,0.000007,0.000012,0.000057,0.008497
2,248754498,01-01,1,1,01:52,1,52,KMIA,US,09:55,...,273.844887,297.149527,4436.0,0.001535,0.002507,0.000015,0.000030,0.000282,0.001843,0.014807
3,248757623,01-01,1,1,08:20,8,20,EGCN,GB,11:06,...,239.456350,290.740698,9600.0,0.000596,0.001405,0.000004,0.000014,0.000015,0.000229,0.006711
4,248763603,01-01,1,1,11:01,11,1,EIDW,IE,13:00,...,251.503365,288.152894,6204.0,0.000521,0.001077,0.000001,0.000024,0.000027,0.000300,0.006392
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
105954,258066302,12-31,12,31,09:36,9,36,LTFJ,TR,13:12,...,223.833881,283.157181,11542.0,0.000606,0.001471,0.000009,0.000013,0.000025,0.000076,0.006653
105955,258068609,12-31,12,31,09:49,9,49,LOWW,AT,19:38,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
105956,258068876,12-31,12,31,09:25,9,25,LTFM,TR,12:24,...,223.619659,288.910314,9305.0,0.000590,0.001525,0.000009,0.000012,0.000021,0.000091,0.006799
105957,258064675,12-31,12,31,10:04,10,4,EHAM,NL,10:55,...,282.867820,289.611221,2838.0,0.003951,0.002964,0.000234,0.000860,0.003821,0.007125,0.008282
105958,258058370,12-31,12,31,09:40,9,40,UBBB,AZ,12:28,...,271.154851,282.230930,3280.0,0.001168,0.001724,0.000010,0.000015,0.000151,0.002237,0.005130

In [8]:
merged_submission_df.to_csv("./data/submission_set_with_trajectories.csv", index=False)
print(f"./data/submission_set_with_trajectories.csv is saved!")

./data/submission_set_with_trajectories.csv is saved!