In [1]:
from sklearn.preprocessing import LabelEncoder
import pandas as pd
import json

<h3>Append processed submission set to processed challenge set</h3>

In [2]:
challenge_set_df = pd.read_csv('./data/challenge_set_with_trajectories.csv')
display(challenge_set_df)

,flight_id,month_day,month,day,actual_offblock_time_hour_minute,actual_offblock_time_hour,actual_offblock_time_minute,adep,country_code_adep,arrival_time_hour_minute,...,temperature_75percentile,temperature_max,specific_humidity_count,specific_humidity_mean,specific_humidity_std,specific_humidity_min,specific_humidity_25percentile,specific_humidity_median,specific_humidity_75percentile,specific_humidity_max
0,248763780,01-01,1,1,13:46,13,46,EGLL,GB,15:04,...,268.945607,288.078244,3614.0,0.001569,0.002304,0.000003,0.000022,0.000114,0.002915,0.008067
1,248760618,01-01,1,1,09:55,9,55,LEBL,ES,19:37,...,221.850708,298.691536,10358.0,0.001025,0.003064,0.000002,0.000028,0.000044,0.000085,0.013049
2,248753824,01-01,1,1,09:39,9,39,ESSA,SE,19:08,...,241.223833,272.897641,12932.0,0.000512,0.000983,0.000003,0.000016,0.000022,0.000190,0.003214
3,248753852,01-01,1,1,11:04,11,4,LSZH,CH,19:32,...,231.613519,286.518770,17534.0,0.000886,0.002158,0.000002,0.000006,0.000018,0.000154,0.008750
4,248755934,01-01,1,1,12:36,12,36,EIDW,IE,13:44,...,275.224544,288.014789,3265.0,0.002256,0.002640,0.000014,0.000029,0.000719,0.004477,0.008008
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
369008,258058361,12-31,12,31,09:38,9,38,LFPG,FR,19:03,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
369009,258071247,12-31,12,31,09:27,9,27,LTFM,TR,12:29,...,221.953594,290.137029,9519.0,0.000698,0.001855,0.000003,0.000024,0.000040,0.000053,0.008280
369010,258059152,12-31,12,31,09:52,9,52,EDDL,DE,11:41,...,248.321020,289.537153,5952.0,0.001027,0.001972,0.000003,0.000020,0.000026,0.000880,0.008802
369011,258072276,12-31,12,31,09:37,9,37,LFPG,FR,11:13,...,258.227824,286.721784,5068.0,0.001184,0.001979,0.000005,0.000022,0.000029,0.001657,0.007904
369012,258069969,12-31,12,31,09:38,9,38,LEMD,ES,17:26,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
submission_set_df = pd.read_csv('./data/submission_set_with_trajectories.csv')
display(submission_set_df)

,flight_id,month_day,month,day,actual_offblock_time_hour_minute,actual_offblock_time_hour,actual_offblock_time_minute,adep,country_code_adep,arrival_time_hour_minute,...,temperature_75percentile,temperature_max,specific_humidity_count,specific_humidity_mean,specific_humidity_std,specific_humidity_min,specific_humidity_25percentile,specific_humidity_median,specific_humidity_75percentile,specific_humidity_max
0,248753821,01-01,1,1,09:44,9,44,LTFJ,TR,12:48,...,224.281845,288.199209,10271.0,0.000368,0.000948,0.000005,0.000021,0.000028,0.000078,0.005248
1,248753822,01-01,1,1,09:45,9,45,EBBR,BE,17:49,...,223.176139,286.131558,15629.0,0.000811,0.001957,0.000003,0.000007,0.000012,0.000057,0.008497
2,248754498,01-01,1,1,01:52,1,52,KMIA,US,09:55,...,273.844887,297.149527,4436.0,0.001535,0.002507,0.000015,0.000030,0.000282,0.001843,0.014807
3,248757623,01-01,1,1,08:20,8,20,EGCN,GB,11:06,...,239.456350,290.740698,9600.0,0.000596,0.001405,0.000004,0.000014,0.000015,0.000229,0.006711
4,248763603,01-01,1,1,11:01,11,1,EIDW,IE,13:00,...,251.503365,288.152894,6204.0,0.000521,0.001077,0.000001,0.000024,0.000027,0.000300,0.006392
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
105954,258066302,12-31,12,31,09:36,9,36,LTFJ,TR,13:12,...,223.833881,283.157181,11542.0,0.000606,0.001471,0.000009,0.000013,0.000025,0.000076,0.006653
105955,258068609,12-31,12,31,09:49,9,49,LOWW,AT,19:38,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
105956,258068876,12-31,12,31,09:25,9,25,LTFM,TR,12:24,...,223.619659,288.910314,9305.0,0.000590,0.001525,0.000009,0.000012,0.000021,0.000091,0.006799
105957,258064675,12-31,12,31,10:04,10,4,EHAM,NL,10:55,...,282.867820,289.611221,2838.0,0.003951,0.002964,0.000234,0.000860,0.003821,0.007125,0.008282
105958,258058370,12-31,12,31,09:40,9,40,UBBB,AZ,12:28,...,271.154851,282.230930,3280.0,0.001168,0.001724,0.000010,0.000015,0.000151,0.002237,0.005130

In [4]:
df_combined = pd.concat([challenge_set_df, submission_set_df], ignore_index=True)
display(df_combined)

,flight_id,month_day,month,day,actual_offblock_time_hour_minute,actual_offblock_time_hour,actual_offblock_time_minute,adep,country_code_adep,arrival_time_hour_minute,...,temperature_75percentile,temperature_max,specific_humidity_count,specific_humidity_mean,specific_humidity_std,specific_humidity_min,specific_humidity_25percentile,specific_humidity_median,specific_humidity_75percentile,specific_humidity_max
0,248763780,01-01,1,1,13:46,13,46,EGLL,GB,15:04,...,268.945607,288.078244,3614.0,0.001569,0.002304,0.000003,0.000022,0.000114,0.002915,0.008067
1,248760618,01-01,1,1,09:55,9,55,LEBL,ES,19:37,...,221.850708,298.691536,10358.0,0.001025,0.003064,0.000002,0.000028,0.000044,0.000085,0.013049
2,248753824,01-01,1,1,09:39,9,39,ESSA,SE,19:08,...,241.223833,272.897641,12932.0,0.000512,0.000983,0.000003,0.000016,0.000022,0.000190,0.003214
3,248753852,01-01,1,1,11:04,11,4,LSZH,CH,19:32,...,231.613519,286.518770,17534.0,0.000886,0.002158,0.000002,0.000006,0.000018,0.000154,0.008750
4,248755934,01-01,1,1,12:36,12,36,EIDW,IE,13:44,...,275.224544,288.014789,3265.0,0.002256,0.002640,0.000014,0.000029,0.000719,0.004477,0.008008
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
474967,258066302,12-31,12,31,09:36,9,36,LTFJ,TR,13:12,...,223.833881,283.157181,11542.0,0.000606,0.001471,0.000009,0.000013,0.000025,0.000076,0.006653
474968,258068609,12-31,12,31,09:49,9,49,LOWW,AT,19:38,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
474969,258068876,12-31,12,31,09:25,9,25,LTFM,TR,12:24,...,223.619659,288.910314,9305.0,0.000590,0.001525,0.000009,0.000012,0.000021,0.000091,0.006799
474970,258064675,12-31,12,31,10:04,10,4,EHAM,NL,10:55,...,282.867820,289.611221,2838.0,0.003951,0.002964,0.000234,0.000860,0.003821,0.007125,0.008282
474971,258058370,12-31,12,31,09:40,9,40,UBBB,AZ,12:28,...,271.154851,282.230930,3280.0,0.001168,0.001724,0.000010,0.000015,0.000151,0.002237,0.005130

<h3>label encode them</h3>

In [5]:
def encode(df: pd.DataFrame, categorical_columns: list[str]) -> pd.DataFrame:
    encoded_df = df.copy()
    label_encoder = LabelEncoder()
    for column in encoded_df.columns:
        if column in categorical_columns:     
            encoded_df[column] = label_encoder.fit_transform(df[column])
            if column == 'aircraft_type':
                aircraft_types_encoding = {encoded: original for original, encoded in zip(label_encoder.classes_, range(len(label_encoder.classes_)))}
                with open('./data/aircraft_types_encoding.json', 'w') as json_file:
                    json.dump(aircraft_types_encoding, json_file, indent=4)
    return encoded_df

In [6]:
categorical_columns = [
    'month_day',
    'actual_offblock_time_hour_minute',
    'adep',
    'country_code_adep',
    'arrival_time_hour_minute',
    'ades', 
    'country_code_ades', 
    'aircraft_type', 
    'wtc', 
    'airline', 
]
encoded_df = encode(df=df_combined, categorical_columns=categorical_columns)
display(encoded_df)

,flight_id,month_day,month,day,actual_offblock_time_hour_minute,actual_offblock_time_hour,actual_offblock_time_minute,adep,country_code_adep,arrival_time_hour_minute,...,temperature_75percentile,temperature_max,specific_humidity_count,specific_humidity_mean,specific_humidity_std,specific_humidity_min,specific_humidity_25percentile,specific_humidity_median,specific_humidity_75percentile,specific_humidity_max
0,248763780,0,1,1,826,13,46,69,37,904,...,268.945607,288.078244,3614.0,0.001569,0.002304,0.000003,0.000022,0.000114,0.002915,0.008067
1,248760618,0,1,1,595,9,55,216,33,1177,...,221.850708,298.691536,10358.0,0.001025,0.003064,0.000002,0.000028,0.000044,0.000085,0.013049
2,248753824,0,1,1,579,9,39,137,88,1148,...,241.223833,272.897641,12932.0,0.000512,0.000983,0.000003,0.000016,0.000022,0.000190,0.003214
3,248753852,0,1,1,664,11,4,338,19,1172,...,231.613519,286.518770,17534.0,0.000886,0.002158,0.000002,0.000006,0.000018,0.000154,0.008750
4,248755934,0,1,1,756,12,36,92,44,824,...,275.224544,288.014789,3265.0,0.002256,0.002640,0.000014,0.000029,0.000719,0.004477,0.008008
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
474967,258066302,364,12,31,576,9,36,384,96,792,...,223.833881,283.157181,11542.0,0.000606,0.001471,0.000009,0.000013,0.000025,0.000076,0.006653
474968,258068609,364,12,31,589,9,49,321,5,1178,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
474969,258068876,364,12,31,565,9,25,385,96,744,...,223.619659,288.910314,9305.0,0.000590,0.001525,0.000009,0.000012,0.000021,0.000091,0.006799
474970,258064675,364,12,31,604,10,4,85,73,655,...,282.867820,289.611221,2838.0,0.003951,0.002964,0.000234,0.000860,0.003821,0.007125,0.008282
474971,258058370,364,12,31,580,9,40,439,7,748,...,271.154851,282.230930,3280.0,0.001168,0.001724,0.000010,0.000015,0.000151,0.002237,0.005130

<h3>split them back into encoded_challenge_set.csv and encoded_submission_set.csv</h3>

In [7]:
def separate_data(original_df: pd.DataFrame, at_index: int):
    encoded_challenge_set = original_df.iloc[:at_index].reset_index(drop=True)
    encoded_submission_set = original_df.iloc[at_index:].reset_index(drop=True)
    return encoded_challenge_set, encoded_submission_set

In [8]:
encoded_challenge_set, encoded_submission_set = separate_data(original_df=encoded_df, at_index=len(challenge_set_df))

<h3>Save to csv</h3>

In [9]:
display(encoded_challenge_set)

,flight_id,month_day,month,day,actual_offblock_time_hour_minute,actual_offblock_time_hour,actual_offblock_time_minute,adep,country_code_adep,arrival_time_hour_minute,...,temperature_75percentile,temperature_max,specific_humidity_count,specific_humidity_mean,specific_humidity_std,specific_humidity_min,specific_humidity_25percentile,specific_humidity_median,specific_humidity_75percentile,specific_humidity_max
0,248763780,0,1,1,826,13,46,69,37,904,...,268.945607,288.078244,3614.0,0.001569,0.002304,0.000003,0.000022,0.000114,0.002915,0.008067
1,248760618,0,1,1,595,9,55,216,33,1177,...,221.850708,298.691536,10358.0,0.001025,0.003064,0.000002,0.000028,0.000044,0.000085,0.013049
2,248753824,0,1,1,579,9,39,137,88,1148,...,241.223833,272.897641,12932.0,0.000512,0.000983,0.000003,0.000016,0.000022,0.000190,0.003214
3,248753852,0,1,1,664,11,4,338,19,1172,...,231.613519,286.518770,17534.0,0.000886,0.002158,0.000002,0.000006,0.000018,0.000154,0.008750
4,248755934,0,1,1,756,12,36,92,44,824,...,275.224544,288.014789,3265.0,0.002256,0.002640,0.000014,0.000029,0.000719,0.004477,0.008008
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
369008,258058361,364,12,31,578,9,38,253,36,1143,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
369009,258071247,364,12,31,567,9,27,385,96,749,...,221.953594,290.137029,9519.0,0.000698,0.001855,0.000003,0.000024,0.000040,0.000053,0.008280
369010,258059152,364,12,31,592,9,52,30,26,701,...,248.321020,289.537153,5952.0,0.001027,0.001972,0.000003,0.000020,0.000026,0.000880,0.008802
369011,258072276,364,12,31,577,9,37,253,36,673,...,258.227824,286.721784,5068.0,0.001184,0.001979,0.000005,0.000022,0.000029,0.001657,0.007904
369012,258069969,364,12,31,578,9,38,222,33,1046,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
encoded_challenge_set.to_csv("./data/encoded_challenge_set.csv", index=False)
print(f"./data/encoded_challenge_set.csv is saved!")

./data/encoded_challenge_set.csv is saved!

In [11]:
display(encoded_submission_set)

,flight_id,month_day,month,day,actual_offblock_time_hour_minute,actual_offblock_time_hour,actual_offblock_time_minute,adep,country_code_adep,arrival_time_hour_minute,...,temperature_75percentile,temperature_max,specific_humidity_count,specific_humidity_mean,specific_humidity_std,specific_humidity_min,specific_humidity_25percentile,specific_humidity_median,specific_humidity_75percentile,specific_humidity_max
0,248753821,0,1,1,584,9,44,384,96,768,...,224.281845,288.199209,10271.0,0.000368,0.000948,0.000005,0.000021,0.000028,0.000078,0.005248
1,248753822,0,1,1,585,9,45,17,11,1069,...,223.176139,286.131558,15629.0,0.000811,0.001957,0.000003,0.000007,0.000012,0.000057,0.008497
2,248754498,0,1,1,112,1,52,190,99,595,...,273.844887,297.149527,4436.0,0.001535,0.002507,0.000015,0.000030,0.000282,0.001843,0.014807
3,248757623,0,1,1,500,8,20,61,37,666,...,239.456350,290.740698,9600.0,0.000596,0.001405,0.000004,0.000014,0.000015,0.000229,0.006711
4,248763603,0,1,1,661,11,1,92,44,780,...,251.503365,288.152894,6204.0,0.000521,0.001077,0.000001,0.000024,0.000027,0.000300,0.006392
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
105954,258066302,364,12,31,576,9,36,384,96,792,...,223.833881,283.157181,11542.0,0.000606,0.001471,0.000009,0.000013,0.000025,0.000076,0.006653
105955,258068609,364,12,31,589,9,49,321,5,1178,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
105956,258068876,364,12,31,565,9,25,385,96,744,...,223.619659,288.910314,9305.0,0.000590,0.001525,0.000009,0.000012,0.000021,0.000091,0.006799
105957,258064675,364,12,31,604,10,4,85,73,655,...,282.867820,289.611221,2838.0,0.003951,0.002964,0.000234,0.000860,0.003821,0.007125,0.008282
105958,258058370,364,12,31,580,9,40,439,7,748,...,271.154851,282.230930,3280.0,0.001168,0.001724,0.000010,0.000015,0.000151,0.002237,0.005130

In [12]:
encoded_submission_set.to_csv("./data/encoded_submission_set.csv", index=False)
print(f"./data/encoded_submission_set.csv is saved!")

./data/encoded_submission_set.csv is saved!