In [15]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import pairwise_distances
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
import pandas as pd
import numpy as np

In [3]:
challenge_set = pd.read_csv('data/processed_challenge_set.csv').drop(['flight_id', 'tow'], axis=1)
challenge_set = challenge_set.sample(n=100, random_state=42)
display(challenge_set)

,month_day,month,day,actual_offblock_time_hour_minute,actual_offblock_time_hour,actual_offblock_time_minute,adep,country_code_adep,arrival_time_hour_minute,arrival_time_hour,arrival_time_minute,ades,country_code_ades,aircraft_type,wtc,airline,flight_duration,taxiout_time,flown_distance
206606,08-08,8,8,11:25,11,25,LFPG,FR,18:30,18,30,KJFK,US,B77W,H,5543e4dc327359ffaf5b9c0e6faaf0e1,415,10,3322
179337,07-15,7,15,18:42,18,42,UBBB,AZ,21:24,21,24,LTFM,TR,A321,M,6351ec1b849adacc0cbb3b1313d8d39b,152,10,1008
234021,08-30,8,30,04:33,4,33,LLBG,IL,06:29,6,29,LTFM,TR,A333,H,6351ec1b849adacc0cbb3b1313d8d39b,101,15,704
274225,10-02,10,2,04:07,4,7,ESSA,SE,07:26,7,26,LGMT,GR,A20N,M,8be5c854fd664bcb97fb543339f74770,184,15,1349
240881,09-05,9,5,06:33,6,33,EKCH,DK,08:20,8,20,EGCC,GB,CRJ9,M,1332254e11e92b4ac6410613b2e86787,97,11,615
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
265575,09-24,9,24,14:20,14,20,EDDK,DE,17:03,17,3,LTFJ,TR,B738,M,6351ec1b849adacc0cbb3b1313d8d39b,148,15,1144
284027,10-09,10,9,11:44,11,44,LEMG,ES,14:38,14,38,LOWW,AT,A320,M,5d407cb11cc29578cc3e292e743f5393,164,11,1224
69094,04-06,4,6,18:48,18,48,LSZH,CH,21:01,21,1,EGLL,GB,BCS3,M,2d5def0a5a844b343ba1b7cc9cb28fa9,121,13,449
9688,01-14,1,14,06:27,6,27,ESSA,SE,07:39,7,39,EFHK,FI,AT76,M,8be5c854fd664bcb97fb543339f74770,57,15,234
138424,06-08,6,8,17:28,17,28,ESNS,SE,18:32,18,32,ESSA,SE,A20N,M,8be5c854fd664bcb97fb543339f74770,59,5,323

In [5]:
categorical_columns = [
    'month_day', 
    'actual_offblock_time_hour_minute', 
    'adep', 
    'country_code_adep',
    'arrival_time_hour_minute',
    'ades', 
    'country_code_ades', 
    'aircraft_type', 
    'wtc', 
    'airline',
]

numerical_columns = [
    'month', 
    'day',
    'actual_offblock_time_hour',
    'actual_offblock_time_minute',
    'arrival_time_hour', 
    'arrival_time_minute',
    'flight_duration', 
    'taxiout_time', 
    'flown_distance'
]

In [8]:
# Define the preprocessing steps
preprocessor = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), numerical_columns),
        ('cat', OneHotEncoder(), categorical_columns)
    ])

# Fit and transform the data
transformed_data = preprocessor.fit_transform(challenge_set)

# Calculate pairwise distances
similarity_matrix = 1 - pairwise_distances(transformed_data, metric='euclidean')

In [9]:
display(similarity_matrix[0, 99])

-5.335063545710878

In [10]:
len(similarity_matrix)

100

In [20]:
similarity_arr = np.array(similarity_matrix, dtype=np.float64)

max_value = np.max(similarity_arr)
print(max_value)

min_value = np.min(similarity_arr)
print(min_value)

1.0
-8.470451803863764